site_name: Project-MeshSegNet

markdown_extensions:
  - codehilite:
      code_background: #ffffff

nav:
  - Home: index.md
  - Deployment: Deployment.md
  - About: about.md

theme: readthedocs
